<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="container">
            <h1>To-Do List</h1>
            <h3>New task:</h3>
            <form action="/add-task" method="post">
                <input class="new-task-input" name="new-task" type="text"><button class="new-button button" type="submit">Add</button></br>
            </form>
            <h3>A list of things to do:</h3>
            <form action="/complete-task" method="post" name="to-do">
                <? echo Example\ViewHelpers\TasksViewHelper::displayUncompletedTasks($uncompletedTasks[0]); ?>
            </form>
            <h3>A list of things I have done:</h3>
            <form action="/delete-task" method="post" name="done">
                <? echo Example\ViewHelpers\TasksViewHelper::displayCompletedTasks($completedTasks[0]); ?>
            </form>
        </div>
    </body>
</html>
