<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="css/style.css" rel="stylesheet" type="text/css">
        <script defer src="js/addNewTask.js"></script>
        <script defer src="js/completeTask.js"></script>
        <script defer src="js/deleteTask.js"></script>
        <script defer src="js/buildList.js"></script>
    </head>
    <body>
        <div class="container">
            <h1>To-Do List</h1>
            <h3>New task:</h3>
            <form id="new-task-form" action="/add-task" method="post">
                <input class="new-task-input" name="new-task" type="text"><button class="new-button button" type="submit">Add</button></br>
            </form>
            <h3>A list of things to do:</h3>
            <div id="complete-task-form" action="/complete-task" method="post" name="to-do">
            </div>
            <h3>A list of things I have done:</h3>
            <div id="delete-task-form" action="/delete-task" method="post" name="done">
            </div>
        </div>
    </body>
</html>
